name: 3d-bpp

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.9.4
  - pip==21.1.2
  - numpy==1.20.2
  - pandas==1.2.4
  - matplotlib==3.4.2
  - tqdm==4.61.0
  - seaborn==0.11.1
  - black==21.5b2
  - nb_black==1.0.7
  - loguru==0.5.3
  - pip:
      - ortools==8.2.8710
      - rectpack==0.2.1
